version: '3.7'
services:
  stream_db:
    image: mysql 
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: streaming_db
      MYSQL_USER: stream_user
      MYSQL_PASSWORD: stream_123
    ports: 
      - 3306:3306
  streaming-app:
    tty: true
    user: '1000:1000'
    stdin_open: true
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app/
    tmpfs:
      - /tmp
    depends_on:
      - stream_db
    ports:
      - "8080:8080"
    environment:
      MYSQL_HOST: stream_db
      MYSQL_DATABASE: streaming_db
      MYSQL_USER: stream_user
      MYSQL_PASSWORD: stream_123
volumes:
  dbdata:
networks:
  default:
    name: zapping 
